language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml

install:
  - composer install

before_script: phpenv config-add .travis/travis-config.ini

script: phpunit -c app/

